import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getLocale } from "next-intl/server";
import { FC, PropsWithChildren } from "react";
import ThemeContextProvider from "@/contexts/theme.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Profile page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={inter.className}>
      <body>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
